# Module 2 (Pandas Import): Importing Files ----

In [1]:
# IMPORTS ----

import pandas as pd

In [12]:
# 1.0 FILES ----

# - Pickle ----

df = pd.read_pickle('../00_data_wrangled/bike_orderlines_wrangled_df.pkl')
df

,order_id,order_line,order_date,model,quantity,price,total_price,bikeshop_name,category_1,category_2,frame_material,city,state
0,1,1,2011-01-07,Jekyll Carbon 2,1,6070,6070,Ithaca Mountain Climbers,Mountain,Over Mountain,Carbon,Ithaca,NY
1,1,2,2011-01-07,Trigger Carbon 2,1,5970,5970,Ithaca Mountain Climbers,Mountain,Over Mountain,Carbon,Ithaca,NY
2,2,1,2011-01-10,Beast of the East 1,1,2770,2770,Kansas City 29ers,Mountain,Trail,Aluminum,Kansas City,KS
3,2,2,2011-01-10,Trigger Carbon 2,1,5970,5970,Kansas City 29ers,Mountain,Over Mountain,Carbon,Kansas City,KS
4,3,1,2011-01-10,Supersix Evo Hi-Mod Team,1,10660,10660,Louisville Race Equipment,Road,Elite Road,Carbon,Louisville,KY
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15639,2000,4,2015-12-25,CAAD Disc Ultegra,1,2660,2660,Austin Cruisers,Road,Elite Road,Aluminum,Austin,TX
15640,2000,5,2015-12-25,Trail 2,1,1350,1350,Austin Cruisers,Mountain,Sport,Aluminum,Austin,TX
15641,2000,6,2015-12-25,CAAD12 105,1,1680,1680,Austin Cruisers,Road,Elite Road,Aluminum,Austin,TX
15642,2000,7,2015-12-25,F-Si Carbon 4,1,2880,2880,Austin Cruisers,Mountain,Cross Country Race,Carbon,Austin,TX
15643,2000,8,2015-12-25,Scalpel-Si 5,1,3200,3200,Austin Cruisers,Mountain,Cross Country Race,Aluminum,Austin,TX

In [16]:

# - CSV ----
csv_df = pd.read_csv('../00_data_wrangled/bike_orderlines_wrangled_df.csv', parse_dates=['order_date'])

csv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15644 entries, 0 to 15643
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      15644 non-null  int64
 1   order_id        15644 non-null  int64
 2   order_line      15644 non-null  int64
 3   order_date      15644 non-null  datetime64[ns]
 4   model           15644 non-null  object
 5   quantity        15644 non-null  int64
 6   price           15644 non-null  int64
 7   total_price     15644 non-null  int64
 8   bikeshop_name   15644 non-null  object
 9   category_1      15644 non-null  object
 10  category_2      15644 non-null  object
 11  frame_material  15644 non-null  object
 12  city            15644 non-null  object
 13  state           15644 non-null  object
dtypes: datetime64[ns](1), int64(6), object(7)
memory usage: 1.7+ MB